/**
 * Which caption track a video starts on when captions are on — resolved on the
 * server from the account's `captionLanguage` setting, so every device agrees
 * and a pick in the player only changes the current video.
 *
 *   1. the chosen language (exact tag, then same base language), unless the
 *      setting is "original";
 *   2. the video's original language;
 *   3. English;
 *   4. the first track.
 *
 * Within a language, human-made tracks beat "(auto-generated)" ones.
 */

export const ORIGINAL_CAPTION_LANGUAGE = "original";

type CaptionLike = { label: string; languageCode: string };

/** YouTube still uses some retired ISO 639 codes ("iw" for Hebrew). */
const LEGACY_BASE: Record<string, string> = { iw: "he", in: "id", ji: "yi" };

function baseLanguage(tag: string | null | undefined): string {
  const base = (tag ?? "").trim().toLowerCase().split(/[-_]/)[0] ?? "";
  return LEGACY_BASE[base] ?? base;
}

function isAutoGenerated(t: CaptionLike): boolean {
  return /\(auto-generated\)/i.test(t.label);
}

/** Best track index in `base`, preferring human-made captions; -1 if none. */
function bestInLanguage(tracks: CaptionLike[], base: string): number {
  if (!base) return -1;
  let auto = -1;
  for (const [i, t] of tracks.entries()) {
    if (baseLanguage(t.languageCode) !== base) continue;
    if (!isAutoGenerated(t)) return i;
    if (auto < 0) auto = i;
  }
  return auto;
}

/**
 * The video's original language: the original audio track's language when the
 * video has several, else the single auto-generated track (YouTube only runs
 * speech recognition on the audio it was uploaded with, dubs aside).
 */
export function originalCaptionLanguage(
  tracks: CaptionLike[],
  originalAudioLanguage: string | null | undefined,
): string | null {
  if (originalAudioLanguage) return baseLanguage(originalAudioLanguage);
  const auto = tracks.filter(isAutoGenerated);
  return auto.length === 1 ? baseLanguage(auto[0]?.languageCode) : null;
}

export function pickDefaultCaptionIndex(
  tracks: CaptionLike[],
  opts: {
    /** Account setting: "original" or a BCP-47 tag. */
    preferred: string | null | undefined;
    originalAudioLanguage?: string | null;
  },
): number {
  if (tracks.length === 0) return -1;
  const preferred = opts.preferred?.trim();
  if (preferred && preferred !== ORIGINAL_CAPTION_LANGUAGE) {
    const exact = tracks.findIndex(
      (t) =>
        t.languageCode.toLowerCase() === preferred.toLowerCase() &&
        !isAutoGenerated(t),
    );
    if (exact >= 0) return exact;
    const sameBase = bestInLanguage(tracks, baseLanguage(preferred));
    if (sameBase >= 0) return sameBase;
  }
  const original = bestInLanguage(
    tracks,
    originalCaptionLanguage(tracks, opts.originalAudioLanguage) ?? "",
  );
  if (original >= 0) return original;
  const english = bestInLanguage(tracks, "en");
  return english >= 0 ? english : 0;
}

/** Languages offered in Settings, besides "original". */
const CAPTION_LANGUAGE_CODES = [
  "en",
  "nl",
  "de",
  "fr",
  "es",
  "it",
  "pt",
  "sv",
  "da",
  "no",
  "fi",
  "pl",
  "cs",
  "tr",
  "ru",
  "uk",
  "el",
  "he",
  "ar",
  "hi",
  "id",
  "ja",
  "ko",
  "zh",
] as const;

export function captionLanguageOptions(
  locale = "en",
): { value: string; label: string }[] {
  let names: Intl.DisplayNames | null = null;
  try {
    names = new Intl.DisplayNames([locale], { type: "language" });
  } catch {
    names = null;
  }
  const langs = CAPTION_LANGUAGE_CODES.map((code) => ({
    value: code,
    label: names?.of(code) ?? code,
  })).sort((a, b) => a.label.localeCompare(b.label));
  return [
    { value: ORIGINAL_CAPTION_LANGUAGE, label: "Video's original language" },
    ...langs,
  ];
}
